name: Vertretung
description: LUL

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.9+33

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.1.2
  cloud_firestore: ^0.16.0
  cloud_functions: ^0.9.0
  dialog_context: ^0.1.1
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_crashlytics: ^0.4.0+1
  firebase_dynamic_links: ^0.7.0+1
  firebase_in_app_messaging: ^0.3.0+1
  firebase_messaging: ^8.0.0-dev.14
  flutter_markdown: ^0.5.0
  html: ^0.14.0+3
  http: ^0.12.0
  intl: ^0.16.1
  introduction_screen: ^1.0.9
  package_info_plus: ^0.6.4  
  provider: ^4.0.5
  share: ^0.6.3+6
  shared_preferences: ^0.5.6+3
  stream_transform: ^2.0.0
  url_launcher: ^5.4.2
  wiredash: ^0.5.0
  flutter_downloader: ^1.5.2
  path_provider: ^1.6.27
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the assets.icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
