name: Build APK based on commit

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "8.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: |
          git clone https://.:${{ secrets.TOKEN}}@github.com/Vinzent03/hiddenData
      - run: |
          mv hiddenData/key.properties android/
          mv hiddenData/Vertretung.jks android/
          mv hiddenData/google-services.json android/app/
          mv hiddenData/wiredashKeys.dart lib/data/
      - run: flutter build apk
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m')"
      - name: rename output apk
        run: mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/Vertretung-${{ steps.date.outputs.date }}.apk

      - uses: actions/upload-artifact@v2
        with:
          path: "build/app/outputs/apk/release/*.apk"
