# This is a basic workflow to help you get started with Actions

name: Build APK based on Tag

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: "stable"
    - run: flutter pub get
    - run: |
        git clone https://.:${{ secrets.TOKEN}}@github.com/Vinzent03/hidedData
    - run: |
        mv hidedData/key.properties android/
        mv hidedData/Vertretung.jks android/
    - run: flutter build apk 
      continue-on-error: true
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifact: "build/app/outputs/apk/release/*.apk"
        token: ${{ secrets.TOKEN }}
